# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4cc0806d0fa0a1c83e21a7248694b4cd9f2a1bbef693b1b1e10c545c7ab76a7f6765785d5942c6c4dfc7c2e594e1fec610f2caa2ffcbd426c6c84ceddffadeb

test:
  secret_key_base: 2223954b30300053c97e7f5472234fb9cda3e9265ba73850e8cfacd75eaba798f56dbe610c7f1d05997cc1eebb01ef7f3abb5281383a0c2d4bd8eb3a0ffc0e09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
